package me.rerere.workspace.x

import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.io.File
import java.nio.file.Files
import kotlin.io.path.readSymbolicLink
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class WorkspaceArchiverTest {

    private fun tempDir(name: String): File =
        Files.createTempDirectory("ws-test-$name").toFile().apply { deleteOnExit() }

    @Test
    fun `roundtrip keeps symlink, exec bit and skips resolv-conf`() {
        val root = tempDir("ws")
        val linux = File(root, "linux").apply { mkdirs() }
        val files = File(root, "files").apply { mkdirs() }

        // 用户区:usr/local/bin/tool(可执行)、etc/my.conf、etc/resolv.conf(应被跳过)
        val bin = File(linux, "usr/local/bin").apply { mkdirs() }
        val tool = File(bin, "tool").apply { writeText("#!/bin/sh\necho hi\n") }
        assertTrue("prep: tool should be executable", tool.setExecutable(true, false))
        val etc = File(linux, "etc").apply { mkdirs() }
        File(etc, "my.conf").writeText("k=v")
        File(etc, "resolv.conf").writeText("nameserver 1.1.1.1 # generated by patcher")
        // 符号链接:usr/local/bin/link -> tool
        Files.createSymbolicLink(File(bin, "link").toPath(), java.nio.file.Paths.get("tool"))
        // files 区
        File(files, "notes.md").writeText("hello")

        val manifest = WorkspaceArchiveManifest(
            id = "id-1",
            root = "id-1",
            name = "My Workspace",
            exportedAtEpochMillis = System.currentTimeMillis(),
            includesUserArea = true,
            includesTools = true,
        )
        val out = ByteArrayOutputStream()
        WorkspaceArchiver.writeArchive(
            workspaceDir = root,
            manifest = manifest,
            output = out,
            virtualFiles = mapOf(
                "tools/tools.txt" to WorkspaceArchiveFile("apt: git\n".toByteArray(), 0x1A4),
                "tools/restore-tools.sh" to WorkspaceArchiveFile("#!/bin/sh\n".toByteArray(), 0x1ED),
            ),
        )

        // 恢复到一个"全新"目录
        val restored = tempDir("restored")
        WorkspaceArchiver.extractArchive(ByteArrayInputStream(out.toByteArray()), restored)

        val restoredLinux = File(restored, "linux")
        val restoredTool = File(restoredLinux, "usr/local/bin/tool")
        assertTrue("usr/local/bin/tool should exist", restoredTool.isFile)
        assertTrue("tool exec bit must survive", restoredTool.canExecute())
        assertEquals("hello", File(restored, "files/notes.md").readText())
        assertEquals("k=v", File(restoredLinux, "etc/my.conf").readText())
        assertFalse("etc/resolv.conf must be excluded", File(restoredLinux, "etc/resolv.conf").exists())

        // 符号链接保真
        val link = File(restoredLinux, "usr/local/bin/link").toPath()
        assertTrue("symlink must survive as symlink", Files.isSymbolicLink(link))
        assertEquals("tool", link.readSymbolicLink().toString())

        // 虚拟文件
        val restoredRestore = File(restored, "tools/restore-tools.sh")
        assertTrue("restore script must be executable", restoredRestore.canExecute())
        assertEquals("apt: git\n", File(restored, "tools/tools.txt").readText())
    }

    @Test
    fun `readManifest returns first entry without draining`() {
        val root = tempDir("ws")
        File(root, "files").mkdirs()
        File(root, "linux").mkdirs()
        val manifest = WorkspaceArchiveManifest(
            id = "x", root = "x", name = "n",
            exportedAtEpochMillis = 1L,
            includesUserArea = false,
            includesTools = false,
        )
        val out = ByteArrayOutputStream()
        WorkspaceArchiver.writeArchive(root, manifest, out)
        val read = WorkspaceArchiver.readManifest(ByteArrayInputStream(out.toByteArray()))
        assertEquals("x", read.id)
        assertEquals("n", read.name)
        assertFalse(read.includesUserArea)
    }

    @Test
    fun `mergeTree overlays source over existing target keeping extras`() {
        val src = tempDir("src")
        File(src, "usr/local/bin").mkdirs()
        File(src, "usr/local/bin/new").writeText("new")
        Files.createSymbolicLink(
            File(src, "usr/local/bin/link").toPath(),
            java.nio.file.Paths.get("new"),
        )
        val dst = tempDir("dst")
        File(dst, "usr/local/bin").mkdirs()
        File(dst, "usr/local/bin/existing").writeText("existing")
        File(dst, "usr/local/bin/extra").writeText("keep")

        WorkspaceArchiver.mergeTree(src, dst)

        assertEquals("new", File(dst, "usr/local/bin/new").readText())
        assertEquals("existing", File(dst, "usr/local/bin/existing").readText())
        assertTrue("target extra file must be kept", File(dst, "usr/local/bin/extra").exists())
        assertTrue(
            "symlink must be recreated",
            Files.isSymbolicLink(File(dst, "usr/local/bin/link").toPath()),
        )
    }

    @Test
    fun `user area only contains declared top dirs`() {
        // linux/usr 存在但 usr/local 不存在 → 不打包 usr
        val root = tempDir("ws")
        File(root, "linux/usr/share").mkdirs()
        File(root, "linux/etc").mkdirs()
        File(root, "files").mkdirs()
        File(root, "files/a.txt").writeText("a")
        val manifest = WorkspaceArchiveManifest(
            id = "i", root = "i", name = "n",
            exportedAtEpochMillis = 0L,
            includesUserArea = true,
        )
        val out = ByteArrayOutputStream()
        WorkspaceArchiver.writeArchive(root, manifest, out)
        val restored = tempDir("r")
        WorkspaceArchiver.extractArchive(ByteArrayInputStream(out.toByteArray()), restored)
        assertTrue("linux/etc should be present", File(restored, "linux/etc").isDirectory)
        assertFalse(
            "usr/share is distro body, not user area",
            File(restored, "linux/usr/share").exists(),
        )
        assertTrue("files/a.txt should be present", File(restored, "files/a.txt").isFile)
    }
}
